<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Clip Video</title>
	<link rel="stylesheet" href="../../css/modal.css">
	<link rel="shortcut icon" href="../../img/logo.png">
</head>
<body>
<div id="bodyContainer">
<div class="modal">
	<div class="modalBox clip__modal">   
            <div class="modal__title">
                <div class="contents__img">
                    <img src="../../img/video/clip.jpg">
                </div>
                <div class="contents__title__back modal__contents__title">
                    <p>IU CLIP</p>
                </div>
            </div>
            
            <div class="modal__contents">
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/0SQOmwa25dw?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/JtFI8dtPvxI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/3iM_06QeZi8?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="1021" height="538" src="https://www.youtube.com/embed/sAbU4fAqjZk?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/OcVmaIlHZ1o?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/tJM0yIbg8iQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/HRQpNxFFkhA?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/o_nxIQTM_B0?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/yqtCGojXEpM?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/RCThRT8QPIA?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/mcnFWBLrdCs?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/hngml3y2Rq8?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/8H1D7XUPNFI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/FAI2wj2JGCI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/DFzPmaNb7fk?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/qLKTlSTdJ5U?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/Xco5vbBmF5c?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/gxS0nz0Ymec?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/UdSXomBAWOQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/TqDFWW6FgVk?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/wZLanAhIVkM?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/aykRAr_iRM4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/m7mvpe1fVa4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/gr4dtauuFzs?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/8zsYZFvKniw?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/nyLoEv1ToX0?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="717" height="538" src="https://www.youtube.com/embed/g0U95UErodo?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/TRTquokWSCw?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/zfRs5hJuh98?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/L1JUfCyeT5E?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/6pFJDR4myaQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/LpijXpZt6F8?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/lisyoBbA18M?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/yU-JO0yAFSg?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/4L-H_cXSNhQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/aTIltcUju4I?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/CI271RQZcGA?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/G_lnyDrFFRc?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/uwGSEUiXyOw?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/x2axFT4WzIc?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/GIHFQhOTbw4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/r7CZQQ0cgQw?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/e2QNxMWSuJc?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="717" height="538" src="https://www.youtube.com/embed/BqclxkxCwos?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/mxJmvbaC104?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/4ZXtY2ix4BM?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="807" height="538" src="https://www.youtube.com/embed/CIkTCO7xgsQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/_3mosc4p-c8?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="717" height="538" src="https://www.youtube.com/embed/gc1yIMrDRAo?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="807" height="538" src="https://www.youtube.com/embed/7_fHs3iYAiI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
            </div>
        </div>
  </div>
</div>
</body>
</html>