<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>IUTV Video</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="../../css/modal.css">
	<link rel="shortcut icon" href="../../img/logo.png">
</head>
<body>
<div id="bodyContainer">
<div class="modal">
	<div class="modalBox iutv__modal">   
            <div class="modal__title">
                <div class="contents__img">
                    <img src="../../img/video/iutv.jpg">
                </div>
                <div class="contents__title__back modal__contents__title">
                    <p>IU TV</p>
                </div>
            </div>
            
            <div class="modal__contents">
                <div class="modal__contents__video">     <iframe width="956" height="538" src="https://www.youtube.com/embed/ECZHKqbasBU?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/5eW6NarieZk?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/oN5GJQK6Taw?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/rfjnzoYLvIU?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/iMPUsHbaXLw?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/b_ygRc5qOPc?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/ZAghZAZ23x8?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/Saq93gLaH9I?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/kvrz_ymT6yQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/LPwxjynAwLI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/otKp1qoF7bI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/pYmGMKypgvE?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/82bLUsKfUmM?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/J8f6QpYJPEQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/zq1_VzTeScE?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/b0zf8S34DrI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/sG1Ewb4fCMQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/OBecbKbtcbI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/V6PCNfWpIA0?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/gHvyC6padH0?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/7Zb9uRLMv1c?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/kuvmNhtqkUI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/edxKTS_KG1c?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/O-5vkEzzpMc?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/5pe4yVuwdY0?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/LEFqwEKfA7w?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/VA7gog7yHqo?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/XNBXSwIBBig?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/kUsCuCiUVs0?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/tBk9Mv6YQbg?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/aStTtxiKNkg?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/hox6OpioFf0?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/mJUvc5sq-VE?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/RARzI_03P_M?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/AR81MgES2z4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/yzGyKusl_G4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/hh4gznMjw54?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/IMht52PJ1PA?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/2LVYavV5xX4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/FGQzGzoLiu0?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/eFBgN6aZ-iM?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/cLKuEmHDcm4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/nD7E_TNOZRI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/LxSEBuRl_mQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/oR6XxQRis0A?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/yLtmS_tHEcc?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/n7YIcu_eZMY?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/IApJcc9i9b0?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/ERXd9gtqm9w?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/-CoHIM7QTHw?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/opRUrc4N938?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/mnXwS7yCKGQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/PbvFY4xY5WQ?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/rvZ-4phCfqc?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/baxd1fkqp90?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/UWi5JUTsgl4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/W_4jEim1KU4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/Y3V8XSi46jM?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/JxiJ1_6meOU?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/fYM0xVGAn9g?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/UCWve8Pzrfw?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/VIKF2kQIPGo?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/dot1cSCy0o4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/rxySSbWKHyY?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/qBgaCfF8SHg?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/qWxYInLscp8?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/EGehoIJ1P4E?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/-tgX__Ys6zI?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/lXc3f_95W_Q?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/pWMlbn8H6n4?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/lCag-Yk7iT0?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/Z059p6oT2SU?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/U9l2jCrNYdM?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                <div class="modal__contents__video">    <iframe width="956" height="538" src="https://www.youtube.com/embed/qUL6vnoRX_s?controls=2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
            </div>
        </div>
    </div>
</div>        
</body>
</html>